name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*' # All tags kick off a new container build Save history ad 5.0.x etc
  # Run tests for any PRs.
  pull_request:

env:
  BUILD_PLATFORM: |
    linux/arm/v6
    linux/arm/v7
    linux/arm64
    linux/amd64


jobs:
  build:
    env:
      IMAGE_NAME: fritzbox_exporter
      # Enable Docker Buildkit
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
